In [2]:
x= rand(5)

5-element Array{Float64,1}:
 0.6907340380389653
 0.4238459010767319
 0.7674535112222407
 0.5900014296793135
 0.7194355186397481

In [5]:
using Statistics

In [2]:
using DelimitedFiles

In [6]:
A=readdlm("wdbc.txt" , ',' , Float64,'\n')

569×32 Array{Float64,2}:
 842302.0        0.0  17.99   10.38  …  0.7119  0.2654   0.4601  0.1189
 842517.0        0.0  20.57   17.77     0.2416  0.186    0.275   0.08902
      8.43009e7  0.0  19.69   21.25     0.4504  0.243    0.3613  0.08758
      8.43483e7  0.0  11.42   20.38     0.6869  0.2575   0.6638  0.173
      8.43584e7  0.0  20.29   14.34     0.4     0.1625   0.2364  0.07678
 843786.0        0.0  12.45   15.7   …  0.5355  0.1741   0.3985  0.1244
 844359.0        0.0  18.25   19.98     0.3784  0.1932   0.3063  0.08368
      8.44582e7  0.0  13.71   20.83     0.2678  0.1556   0.3196  0.1151
 844981.0        0.0  13.0    21.82     0.539   0.206    0.4378  0.1072
      8.4501e7   0.0  12.46   24.04     1.105   0.221    0.4366  0.2075
 845636.0        0.0  16.02   23.24  …  0.1459  0.09975  0.2948  0.08452
      8.461e7    0.0  15.78   17.89     0.3965  0.181    0.3792  0.1048
 846226.0        0.0  19.17   24.8      0.3639  0.1767   0.3176  0.1023
      ⋮                            

In [67]:
y=A[:,2]
X=A[:,3:12]
X1=X[y.==0,:]
size(X1)

(212, 10)

In [77]:
π

π = 3.1415926535897...

In [72]:
# chiều của ma trận X
N,D= size(X)
θ=zeros(2)
θ[1]=sum(y.==0)/N
print(θ[1])
θ[2]=sum(y.==1)/N
K=length(unique(y))
D

0.0

10

In [73]:
X=A[:,3:12]
y=A[:,2]
y=y.+1

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [74]:
function train(X,y)
    N,D= size(X)
    K=length(unique(y))
    μ=zeros(K,D)
    σ=zeros(K,D)
    θ=zeros(K)
    for k= 1: K
        θ[k]=sum(y.==k)/N
        X_k=X[y.==k,:]
        μ[k,:]=mean(X_k, dims=1)
        σ[k,:]=std(X_k, dims=1)
    end
    (θ,μ,σ)
end

train (generic function with 1 method)

In [76]:
(θ,μ,σ)= train(X,y)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.19290896226415097 0.06268009433962264; 12.146523809523813 17.914761904761903 … 0.17418599439775911 0.0628673949579832], [3.203971100779367 3.779469920776341 … 0.027638092143030174 0.007573315024808589; 1.7805116461410393 3.995124593675911 … 0.02480675820679328 0.0067473428139250636])

In [102]:
# xây dựng hàm dự đoán
function predict(θ,μ,σ,Xnew)
    # dự đoán dựa vào công thức xác suất đầy đủ
    # p(y=k|x)=p(y=k)*p(x|y=k) log 2 vế để mất phép nhân chuyển về phép cộng đây là ước lượng hợp lý cực đại
    K= length(θ)
    t=zeros(K)
    for k= 1:K
        α=log(θ[k])
        tmp=(Xnew - μ[k,:])./σ[k,:] # chia từng giá trị của vector tử cho vector mẫu
        tmp1=tmp*tmp'
        β=sum(log.(σ[k,:])) - sum(tmp1/2)
        t[k]= α + β
    end
    argmax(t)
end

predict (generic function with 1 method)

In [113]:
Xnew=X[400,:]
print(predict(θ,μ,σ,Xnew))
y[400]

2

2.0

In [129]:
# xây dựng hàm accuracy
function accuracy(y,X,θ,μ,σ)
    ŷ=zeros(length(y))
    for i=1:length(y)
        ŷ[i]=predict(θ,μ,σ,X[i,:])
    end
    acc = sum(y.== ŷ)/ length(y)
    return acc
end

accuracy (generic function with 1 method)

In [130]:
acc=accuracy(y,X,θ,μ,σ)

0.9103690685413005