In [1]:
using DelimitedFiles
using Plots

In [2]:
A = readdlm("data/admission.txt",',',Float64,'\n')

100×3 Array{Float64,2}:
 34.6237  78.0247  0.0
 30.2867  43.895   0.0
 35.8474  72.9022  0.0
 60.1826  86.3086  1.0
 79.0327  75.3444  1.0
 45.0833  56.3164  0.0
 61.1067  96.5114  1.0
 75.0247  46.554   1.0
 76.0988  87.4206  1.0
 84.4328  43.5334  1.0
 95.8616  38.2253  0.0
 75.0137  30.6033  0.0
 82.3071  76.482   1.0
  ⋮                
 78.6354  96.6474  1.0
 52.348   60.7695  0.0
 94.0943  77.1591  1.0
 90.4486  87.5088  1.0
 55.4822  35.5707  0.0
 74.4927  84.8451  1.0
 89.8458  45.3583  1.0
 83.4892  48.3803  1.0
 42.2617  87.1039  1.0
 99.315   68.7754  1.0
 55.34    64.9319  1.0
 74.7759  89.5298  1.0

In [3]:
X = A[:,1:2]

100×2 Array{Float64,2}:
 34.6237  78.0247
 30.2867  43.895
 35.8474  72.9022
 60.1826  86.3086
 79.0327  75.3444
 45.0833  56.3164
 61.1067  96.5114
 75.0247  46.554
 76.0988  87.4206
 84.4328  43.5334
 95.8616  38.2253
 75.0137  30.6033
 82.3071  76.482
  ⋮       
 78.6354  96.6474
 52.348   60.7695
 94.0943  77.1591
 90.4486  87.5088
 55.4822  35.5707
 74.4927  84.8451
 89.8458  45.3583
 83.4892  48.3803
 42.2617  87.1039
 99.315   68.7754
 55.34    64.9319
 74.7759  89.5298

In [4]:
y = A[:,3]

100-element Array{Float64,1}:
 0.0
 0.0
 0.0
 1.0
 1.0
 0.0
 1.0
 1.0
 1.0
 1.0
 0.0
 0.0
 1.0
 ⋮
 1.0
 0.0
 1.0
 1.0
 0.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [5]:
X_hc = [ones(length(y)) X]

100×3 Array{Float64,2}:
 1.0  34.6237  78.0247
 1.0  30.2867  43.895
 1.0  35.8474  72.9022
 1.0  60.1826  86.3086
 1.0  79.0327  75.3444
 1.0  45.0833  56.3164
 1.0  61.1067  96.5114
 1.0  75.0247  46.554
 1.0  76.0988  87.4206
 1.0  84.4328  43.5334
 1.0  95.8616  38.2253
 1.0  75.0137  30.6033
 1.0  82.3071  76.482
 ⋮             
 1.0  78.6354  96.6474
 1.0  52.348   60.7695
 1.0  94.0943  77.1591
 1.0  90.4486  87.5088
 1.0  55.4822  35.5707
 1.0  74.4927  84.8451
 1.0  89.8458  45.3583
 1.0  83.4892  48.3803
 1.0  42.2617  87.1039
 1.0  99.315   68.7754
 1.0  55.34    64.9319
 1.0  74.7759  89.5298

In [20]:
#sigmoid function
function sigmoid(X,θ)
    z = X*θ
    h = 1 ./ (1 .+ exp.(z))
end

sigmoid (generic function with 1 method)

In [18]:
θ = ones(3,length(unique(y)))

3×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [21]:
sigmoid(X_hc,θ)

100×2 Array{Float64,2}:
 4.39691e-50  4.39691e-50
 2.23357e-33  2.23357e-33
 2.16946e-48  2.16946e-48
 8.81874e-65  8.81874e-65
 3.31572e-68  3.31572e-68
 3.37596e-45  3.37596e-45
 1.29729e-69  1.29729e-69
 5.8173e-54   5.8173e-54
 3.54937e-72  3.54937e-72
 9.7878e-57   9.7878e-57
 2.15047e-59  2.15047e-59
 4.97576e-47  4.97576e-47
 4.02265e-70  4.02265e-70
 ⋮            
 2.76268e-77  2.76268e-77
 2.7504e-50   2.7504e-50
 1.5534e-75   1.5534e-75
 1.90464e-78  1.90464e-78
 1.05184e-40  1.05184e-40
 2.32362e-70  2.32362e-70
 7.03583e-60  7.03583e-60
 1.97484e-58  1.97484e-58
 2.41524e-57  2.41524e-57
 3.67252e-74  3.67252e-74
 2.14911e-53  2.14911e-53
 1.61675e-72  1.61675e-72

In [ ]:
#loss function 
function loss(X,y,w,λ,θ)
    g = sigmoid(X,θ)
    J = -w'*(y'*log.(g) + )
end