In [1]:
using DelimitedFiles
using Plots
using Optim

In [2]:
A= readdlm("iris_flower/iris-train.txt")

130×5 Array{Float64,2}:
 1.0  5.1  3.5  1.4  0.2
 1.0  4.7  3.2  1.3  0.2
 1.0  4.6  3.1  1.5  0.2
 1.0  5.0  3.6  1.4  0.2
 1.0  4.6  3.4  1.4  0.3
 1.0  4.4  2.9  1.4  0.2
 1.0  4.9  3.1  1.5  0.1
 1.0  5.4  3.7  1.5  0.2
 1.0  4.8  3.4  1.6  0.2
 1.0  4.8  3.0  1.4  0.1
 1.0  4.3  3.0  1.1  0.1
 1.0  5.8  4.0  1.2  0.2
 1.0  5.7  4.4  1.5  0.4
 ⋮                   
 3.0  6.1  2.6  5.6  1.4
 3.0  6.3  3.4  5.6  2.4
 3.0  6.0  3.0  4.8  1.8
 3.0  6.9  3.1  5.4  2.1
 3.0  6.7  3.1  5.6  2.4
 3.0  6.9  3.1  5.1  2.3
 3.0  5.8  2.7  5.1  1.9
 3.0  6.7  3.3  5.7  2.5
 3.0  6.3  2.5  5.0  1.9
 3.0  6.5  3.0  5.2  2.0
 3.0  6.2  3.4  5.4  2.3
 3.0  5.9  3.0  5.1  1.8

In [3]:
y= Int.(A[:,1])
X=[ones(length(y)) A[:,2:4]]

130×4 Array{Float64,2}:
 1.0  5.1  3.5  1.4
 1.0  4.7  3.2  1.3
 1.0  4.6  3.1  1.5
 1.0  5.0  3.6  1.4
 1.0  4.6  3.4  1.4
 1.0  4.4  2.9  1.4
 1.0  4.9  3.1  1.5
 1.0  5.4  3.7  1.5
 1.0  4.8  3.4  1.6
 1.0  4.8  3.0  1.4
 1.0  4.3  3.0  1.1
 1.0  5.8  4.0  1.2
 1.0  5.7  4.4  1.5
 ⋮              
 1.0  6.1  2.6  5.6
 1.0  6.3  3.4  5.6
 1.0  6.0  3.0  4.8
 1.0  6.9  3.1  5.4
 1.0  6.7  3.1  5.6
 1.0  6.9  3.1  5.1
 1.0  5.8  2.7  5.1
 1.0  6.7  3.3  5.7
 1.0  6.3  2.5  5.0
 1.0  6.5  3.0  5.2
 1.0  6.2  3.4  5.4
 1.0  5.9  3.0  5.1

In [26]:
# xây dựng hàm softmax
function softmax(X,θ)
    a= exp.(θ*X')
    t= a ./ (sum(a, dims=1))
    return t
end

classify (generic function with 1 method)

In [4]:
# xây dựng hàm loss 
function loss(X,y,θ)
    N,D= size(X)
    l=θ*X' - log.(exp.())   
end

loss (generic function with 1 method)

In [16]:
x=[1 2 3 4; 3 4 5 6]
x 
t= sum(x, dims=1)
print(t)
k= x ./ (sum(x, dims=1))

[4 6 8 10]

2×4 Array{Float64,2}:
 0.25  0.333333  0.375  0.4
 0.75  0.666667  0.625  0.6