In [1]:
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

In [3]:
print('Number of  classer : %d' %len(np.unique(iris_y)))
print('Number of data points : %d' %len(iris_y))

Number of  classer : 3
Number of data points : 150


In [4]:
X0 = iris_X[iris_y == 0,:]
print('Simple of class 0 :\n', X0[:5,:])

X1 = iris_X[iris_y == 1,:]
print('Simple of class 1 :\n', X1[:5,:])

X2 = iris_X[iris_y == 2,:]
print('Simple of class 2 :\n', X2[:5,:])

Simple of class 0 :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Simple of class 1 :
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
Simple of class 2 :
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


In [5]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=50)

print("Trainning size : %d" %len(y_train))
print("Test size      : %d" %len(y_test))

Trainning size : 100
Test size      : 50


In [ ]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 1, p =2)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print