A. Mang 1 chieu

In [1]:
import numpy as np

In [2]:
number_vector = np.array([1, 2, 3, 4])

In [3]:
number_vector.shape

(4,)

In [13]:
number_matrix = np.array([[1 , 2, 3], [4, 5, 6]])

In [14]:
number_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
number_matrix.shape

(2, 3)

In [22]:
number_3D_matrix = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [23]:
number_3D_matrix

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [24]:
number_3D_matrix.shape

(2, 2, 3)

In [25]:
#np.zeros()
number_1D_zeros = np.zeros((7, ))

In [26]:
number_1D_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [27]:
#np.ones()
number_1D_ones = np.ones((3, ))

In [28]:
number_1D_ones

array([1., 1., 1.])

In [32]:
#np.full
number_1D_Towsevens = np.full((6, ), 27)

In [33]:
number_1D_Towsevens

array([27, 27, 27, 27, 27, 27])

B. Mang 2 chieu

In [34]:
number_2D_zeros = np.zeros((7, 7))

In [35]:
number_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [36]:
#np.one()
number_2D_ones = np.ones((6, 5))

In [37]:
number_2D_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
#np.full()
number_2D_eights = np.full((8, 8), 8)

In [39]:
number_2D_eights

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

C. Mang 3 chieu

In [40]:
number_3D_zeros = np.zeros((4, 2, 3))

In [41]:
number_3D_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
number_3D_ones = np.ones((3, 4, 5))

In [45]:
number_3D_ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [46]:
number_3D_twenties = np.full((3, 4, 5), 20)

In [47]:
number_3D_twenties

array([[[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]]])

In [48]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
#Tao gia tri chay tu 0 den 10
number_1D_range_10 = np.arange(10)

In [50]:
number_1D_range_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
number_1D_range_30_step2 = np.

In [2]:
number_1D = np.arange(10)

In [4]:
for item in np.nditer(number_1D):
    print(item)

0
1
2
3
4
5
6
7
8
9


In [6]:
number_2D = np.random.random((3,2))

In [7]:
for item in number_2D:
    print(item)

[0.2034779 0.8054039]
[0.85405985 0.48867332]
[0.88779113 0.24379437]


In [8]:
for item in np.nditer(number_2D):
    print(item)

0.20347790486941442
0.8054038971210236
0.8540598548132582
0.48867332451445333
0.8877911267849512
0.24379436940642696


In [12]:
for item in np.nditer(number_2D, op_flags = ['readwrite']):
    item[...] = item ** 2

In [14]:
number_1D

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])