In [2]:
using Statistics
using DelimitedFiles

In [4]:
A = readdlm("./data/wdbc.txt",',')

569×32 Array{Float64,2}:
 842302.0        0.0  17.99   10.38  …  0.7119  0.2654   0.4601  0.1189
 842517.0        0.0  20.57   17.77     0.2416  0.186    0.275   0.08902
      8.43009e7  0.0  19.69   21.25     0.4504  0.243    0.3613  0.08758
      8.43483e7  0.0  11.42   20.38     0.6869  0.2575   0.6638  0.173
      8.43584e7  0.0  20.29   14.34     0.4     0.1625   0.2364  0.07678
 843786.0        0.0  12.45   15.7   …  0.5355  0.1741   0.3985  0.1244
 844359.0        0.0  18.25   19.98     0.3784  0.1932   0.3063  0.08368
      8.44582e7  0.0  13.71   20.83     0.2678  0.1556   0.3196  0.1151
 844981.0        0.0  13.0    21.82     0.539   0.206    0.4378  0.1072
      8.4501e7   0.0  12.46   24.04     1.105   0.221    0.4366  0.2075
 845636.0        0.0  16.02   23.24  …  0.1459  0.09975  0.2948  0.08452
      8.461e7    0.0  15.78   17.89     0.3965  0.181    0.3792  0.1048
 846226.0        0.0  19.17   24.8      0.3639  0.1767   0.3176  0.1023
      ⋮                            

In [10]:
y = A[:,2].+1

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [12]:
m=(sum(y.==1))/length(y)

0.37258347978910367

In [8]:
X  = A[:,3:end]

569×30 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.7119  0.2654   0.4601  0.1189
 20.57   17.77  132.9   1326.0  0.08474     0.2416  0.186    0.275   0.08902
 19.69   21.25  130.0   1203.0  0.1096      0.4504  0.243    0.3613  0.08758
 11.42   20.38   77.58   386.1  0.1425      0.6869  0.2575   0.6638  0.173
 20.29   14.34  135.1   1297.0  0.1003      0.4     0.1625   0.2364  0.07678
 12.45   15.7    82.57   477.1  0.1278   …  0.5355  0.1741   0.3985  0.1244
 18.25   19.98  119.6   1040.0  0.09463     0.3784  0.1932   0.3063  0.08368
 13.71   20.83   90.2    577.9  0.1189      0.2678  0.1556   0.3196  0.1151
 13.0    21.82   87.5    519.8  0.1273      0.539   0.206    0.4378  0.1072
 12.46   24.04   83.97   475.9  0.1186      1.105   0.221    0.4366  0.2075
 16.02   23.24  102.7    797.8  0.08206  …  0.1459  0.09975  0.2948  0.08452
 15.78   17.89  103.6    781.0  0.0971      0.3965  0.181    0.3792  0.1048
 19.17   24.8   132.4   1123.0  0.0974      0.3639  0.1767 

In [15]:
function train(X,y)
    N,D = size(X)
    K = length(unique(y))
    θ = zeros(K) # 
    μ = zeros(K,D) #  k hang va xac suat trung binh fitter 
    σ = zeros(K,D) # sai so tren tung fitter
    for i=1:K 
        θ[i] = (sum(y.==i))/length(y)
        X_i = X[y.==i,:]
        μ[i,:] = mean(X_i,dims=1) #dims=1(chieu cot) dims=2(chieu hang)
        σ[i,:] = std(X_i,dims=1) #tinh do lech chuan cua tung thanh phan 
    end
    return θ, μ, σ
end

train (generic function with 1 method)

In [30]:
θ, μ, σ=train(X,y)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.32346792452830186 0.09152995283018867; 12.146523809523813 17.914761904761903 … 0.27024593837535005 0.07944207282913165], [3.203971100779367 3.779469920776341 … 0.0746849560686125 0.02155288851442655; 1.7805116461410393 3.995124593675911 … 0.0417447664287058 0.013804045110823396])

θ

In [20]:
θ

2-element Array{Float64,1}:
 0.37258347978910367
 0.6274165202108963

In [21]:
σ

2×30 Array{Float64,2}:
 3.20397  3.77947  21.8547  367.938  …  0.0463078  0.074685   0.0215529
 1.78051  3.99512  11.8074  134.287     0.0357974  0.0417448  0.013804

In [22]:
μ

2×30 Array{Float64,2}:
 17.4628  21.6049  115.365   978.376  …  0.182237   0.323468  0.09153
 12.1465  17.9148   78.0754  462.79      0.0744443  0.270246  0.0794421

In [32]:
function classify(xNew,θ,μ,σ)
    K = length(θ)
    t = zeros(K)
    for i = 1:K
        α = log(θ[i])
        temps = (xNew - μ[i,:])./(σ[i,:])
        β_i = temps'*temps #tong cua binh phuong thu hai
        H_i = -log.(σ[i,:]) #tong cua log thu nhat
        t[i] = α + sum(H_i) - sum(β_i)/2
    end
    return argmax(t)
end

classify (generic function with 1 method)

In [33]:
classify(X[1,:],θ,μ,σ)

1

In [35]:
function accurency(X,y,θ,μ,σ)
    ŷ = zeros(length(y))
    for i=1:length(ŷ)
        ŷ[i]=classify(X[i,:],θ,μ,σ)
    end
    t=sum(y.==ŷ)/length(y)
    return t
end

accurency (generic function with 1 method)

In [36]:
accurency(X,y,θ,μ,σ)

0.9402460456942003