In [2]:
x = rand(5)

5-element Array{Float64,1}:
 0.4506843835985943
 0.8279585202438178
 0.24021655100449624
 0.6705868179263774
 0.44107466244340165

In [3]:
length(x)

5

In [4]:
using DelimitedFiles #thu vien doc du lieu

In [5]:
A = readdlm("data/wdbc.txt", ',', Float64, '\n')

569×32 Array{Float64,2}:
 842302.0        0.0  17.99   10.38  …  0.7119  0.2654   0.4601  0.1189
 842517.0        0.0  20.57   17.77     0.2416  0.186    0.275   0.08902
      8.43009e7  0.0  19.69   21.25     0.4504  0.243    0.3613  0.08758
      8.43483e7  0.0  11.42   20.38     0.6869  0.2575   0.6638  0.173
      8.43584e7  0.0  20.29   14.34     0.4     0.1625   0.2364  0.07678
 843786.0        0.0  12.45   15.7   …  0.5355  0.1741   0.3985  0.1244
 844359.0        0.0  18.25   19.98     0.3784  0.1932   0.3063  0.08368
      8.44582e7  0.0  13.71   20.83     0.2678  0.1556   0.3196  0.1151
 844981.0        0.0  13.0    21.82     0.539   0.206    0.4378  0.1072
      8.4501e7   0.0  12.46   24.04     1.105   0.221    0.4366  0.2075
 845636.0        0.0  16.02   23.24  …  0.1459  0.09975  0.2948  0.08452
      8.461e7    0.0  15.78   17.89     0.3965  0.181    0.3792  0.1048
 846226.0        0.0  19.17   24.8      0.3639  0.1767   0.3176  0.1023
      ⋮                            

In [6]:
y = A[:, 2] .+ 1

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [7]:
X = A[:, 3:12]

569×10 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.3001   0.1471   0.2419  0.07871
 20.57   17.77  132.9   1326.0  0.08474     0.0869   0.07017  0.1812  0.05667
 19.69   21.25  130.0   1203.0  0.1096      0.1974   0.1279   0.2069  0.05999
 11.42   20.38   77.58   386.1  0.1425      0.2414   0.1052   0.2597  0.09744
 20.29   14.34  135.1   1297.0  0.1003      0.198    0.1043   0.1809  0.05883
 12.45   15.7    82.57   477.1  0.1278   …  0.1578   0.08089  0.2087  0.07613
 18.25   19.98  119.6   1040.0  0.09463     0.1127   0.074    0.1794  0.05742
 13.71   20.83   90.2    577.9  0.1189      0.09366  0.05985  0.2196  0.07451
 13.0    21.82   87.5    519.8  0.1273      0.1859   0.09353  0.235   0.07389
 12.46   24.04   83.97   475.9  0.1186      0.2273   0.08543  0.203   0.08243
 16.02   23.24  102.7    797.8  0.08206  …  0.03299  0.03323  0.1528  0.05697
 15.78   17.89  103.6    781.0  0.0971      0.09954  0.06606  0.1842  0.06082
 19.17   24.8   132.4   1123.0  0.0974 

In [8]:
size(X)

(569, 10)

In [9]:
X_all = A[:, 3:end]

569×30 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.7119  0.2654   0.4601  0.1189
 20.57   17.77  132.9   1326.0  0.08474     0.2416  0.186    0.275   0.08902
 19.69   21.25  130.0   1203.0  0.1096      0.4504  0.243    0.3613  0.08758
 11.42   20.38   77.58   386.1  0.1425      0.6869  0.2575   0.6638  0.173
 20.29   14.34  135.1   1297.0  0.1003      0.4     0.1625   0.2364  0.07678
 12.45   15.7    82.57   477.1  0.1278   …  0.5355  0.1741   0.3985  0.1244
 18.25   19.98  119.6   1040.0  0.09463     0.3784  0.1932   0.3063  0.08368
 13.71   20.83   90.2    577.9  0.1189      0.2678  0.1556   0.3196  0.1151
 13.0    21.82   87.5    519.8  0.1273      0.539   0.206    0.4378  0.1072
 12.46   24.04   83.97   475.9  0.1186      1.105   0.221    0.4366  0.2075
 16.02   23.24  102.7    797.8  0.08206  …  0.1459  0.09975  0.2948  0.08452
 15.78   17.89  103.6    781.0  0.0971      0.3965  0.181    0.3792  0.1048
 19.17   24.8   132.4   1123.0  0.0974      0.3639  0.1767 

In [10]:
size(X_all)

(569, 30)

In [1]:
θ = zeros(2) #tao mang 2*1

2-element Array{Float64,1}:
 0.0
 0.0

In [2]:
size(θ)

(2,)

In [12]:
N, D = size(X)

(569, 10)

In [13]:
K =2

2

In [14]:
μ = zeros(K, D)
σ = zeros(K, D)

2×10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [15]:
using Statistics #chua ham mean

In [16]:
θ[1] = sum(y .== 1)/N
θ[2] = sum(y .== 2)/N
θ

2-element Array{Float64,1}:
 0.37258347978910367
 0.6274165202108963

In [17]:
X_1 = X[y .== 1, :]
X_2 = X[y .==2, :]
μ[1, :] = mean(X_1, dims=1) #dims=1 tinh theo cot =2 tinh theo hang
μ[2, :] = mean(X_2, dims=1)
μ

2×10 Array{Float64,2}:
 17.4628  21.6049  115.365   978.376  …  0.08799    0.192909  0.0626801
 12.1465  17.9148   78.0754  462.79      0.0257174  0.174186  0.0628674

In [18]:
σ[1, :] = std(X_1, dims=1) #ham std dung de tinh ki vong 
σ[2, :] = std(X_2, dims=1)
σ

2×10 Array{Float64,2}:
 3.20397  3.77947  21.8547  367.938  …  0.0343739  0.0276381  0.00757332
 1.78051  3.99512  11.8074  134.287     0.0159088  0.0248068  0.00674734

In [19]:
(θ, μ, σ)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.19290896226415097 0.06268009433962264; 12.146523809523813 17.914761904761903 … 0.17418599439775911 0.0628673949579832], [3.203971100779367 3.779469920776341 … 0.027638092143030174 0.007573315024808589; 1.7805116461410393 3.995124593675911 … 0.02480675820679328 0.0067473428139250636])

In [20]:
function train(X, y)
    N, D = size(X)
    K = length(unique(y)) #lay cac gia tri khac nhau
    θ = zeros(K)
    μ = zeros(K, D)
    σ = zeros(K, D)
    for k=1:K
        θ[k] = sum(y .==k)/N
        X_k = X[y .==k, :]
        μ[k, :] =mean(X_k, dims=1)
        σ[k, :] =std(X_k, dims=1)
    end
    (θ, μ, σ)
end

train (generic function with 1 method)

In [21]:
X 

569×10 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.3001   0.1471   0.2419  0.07871
 20.57   17.77  132.9   1326.0  0.08474     0.0869   0.07017  0.1812  0.05667
 19.69   21.25  130.0   1203.0  0.1096      0.1974   0.1279   0.2069  0.05999
 11.42   20.38   77.58   386.1  0.1425      0.2414   0.1052   0.2597  0.09744
 20.29   14.34  135.1   1297.0  0.1003      0.198    0.1043   0.1809  0.05883
 12.45   15.7    82.57   477.1  0.1278   …  0.1578   0.08089  0.2087  0.07613
 18.25   19.98  119.6   1040.0  0.09463     0.1127   0.074    0.1794  0.05742
 13.71   20.83   90.2    577.9  0.1189      0.09366  0.05985  0.2196  0.07451
 13.0    21.82   87.5    519.8  0.1273      0.1859   0.09353  0.235   0.07389
 12.46   24.04   83.97   475.9  0.1186      0.2273   0.08543  0.203   0.08243
 16.02   23.24  102.7    797.8  0.08206  …  0.03299  0.03323  0.1528  0.05697
 15.78   17.89  103.6    781.0  0.0971      0.09954  0.06606  0.1842  0.06082
 19.17   24.8   132.4   1123.0  0.0974 

In [22]:
y

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [23]:
(θ, μ, σ) = train(X, y)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.19290896226415097 0.06268009433962264; 12.146523809523813 17.914761904761903 … 0.17418599439775911 0.0628673949579832], [3.203971100779367 3.779469920776341 … 0.027638092143030174 0.007573315024808589; 1.7805116461410393 3.995124593675911 … 0.02480675820679328 0.0067473428139250636])

In [24]:
X[100, :]

10-element Array{Float64,1}:
  14.42
  19.77
  94.48
 642.5
   0.09752
   0.1141
   0.09388
   0.05839
   0.1879
   0.0639

In [25]:
y[100]

1.0

In [26]:
X[400, :]

10-element Array{Float64,1}:
  11.8
  17.26
  75.26
 431.9
   0.09087
   0.06232
   0.02853
   0.01638
   0.1847
   0.06019

In [27]:
y[400]

2.0

In [28]:
xNew = X[100, :]

10-element Array{Float64,1}:
  14.42
  19.77
  94.48
 642.5
   0.09752
   0.1141
   0.09388
   0.05839
   0.1879
   0.0639

In [29]:
u = [1 2 3]
u*u'

1×1 Array{Int64,2}:
 14

In [30]:
# Computer posterior probability distribution : P(y = 1|xNew), P(y = 2|xNew)

#log P(y = 1|xNew) ∝ log(prior_1) + log(likelihood_1) = α_1 + β_1
α_1 = log(θ[1])
u = (xNew - μ[1, :])./σ[1 , :]
β_1 = sum(log.(σ[1, :])) + sum(u.*u)/2    #log cua vector

#log P(y = 2|xNew) ∝ log(prior_2) + log(likelihood_2) = α_2 + β_2
α_2 = log(θ[2])
v = (xNew - μ[2, :])./σ[2 , :]
β_2 = sum(log.(σ[2, :])) + sum(v.*v)/2 

-8.098419462134306

In [31]:
α_1 -β_1

6.754347357346591

In [32]:
α_2 - β_2

7.632274809787614

In [33]:
u = rand(5)

5-element Array{Float64,1}:
 0.14656459159435475
 0.8500973514026027
 0.33057223566803984
 0.8763350311135896
 0.08290551697989712

In [34]:
argmax(u)

4

In [35]:
function classify(xNew, θ, μ, σ)
    K = length(θ)
    scores = zeros(K)
    for k = 1 : K
        α_k = log(θ[k])
        u = (xNew - μ[k, :])./σ[k , :]
        β_k = sum(log.(σ[k, :])) + sum(u.*u)/2 
        scores[k]= α_k - β_k
    end
    argmax(scores)
end

classify (generic function with 1 method)

In [36]:
xNew = X[100, :]
yNew = classify(xNew, θ, μ, σ)

2

In [37]:
xNew = X[400, :]
yNew = classify(xNew, θ, μ, σ)

2

In [38]:
ŷ = zeros(N)
for i=1:N
    ŷ[i] = classify(X[i, :], θ, μ, σ)
end

In [39]:
ŷ

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [40]:
accuracy = sum(y.==ŷ)/N

0.9138840070298769

In [41]:
size(X)

(569, 10)

In [42]:
θ

2-element Array{Float64,1}:
 0.37258347978910367
 0.6274165202108963

In [43]:
function evaluate(X, y, θ, μ, σ)
    N = length(y)
    ŷ = zeros(N)
    for i=1:N
        ŷ[i] = classify(X[i, :], θ, μ, σ)
    end
    sum(y .== ŷ)/N
end

evaluate (generic function with 1 method)

In [44]:
evaluate(X, y, θ, μ, σ)

0.9138840070298769

In [45]:
evaluate(X[1:100, :], y[1:100], θ, μ, σ)

0.83

In [46]:
evaluate(X[N-100:end, :], y[N-100:end], θ, μ, σ)

0.9306930693069307

In [47]:
function train1(X, y)
    N, D = size(X)
    K = length(unique(y)) #lay cac gia tri khac nhau
    θ = zeros(K)
    μ = zeros(K, D)
    σ = zeros(K, D)
    for k=1:K
        θ[k] = sum(y .==k)/N
        X_k = X[y .==k, :]
        μ[k, :] =mean(X_k, dims=1)
        σ[k, :] =std(X_k, dims=1)
    end
    (θ, μ, σ)
end

function classify(xNew, θ, μ, σ)
    K = length(θ)
    scores = zeros(K)
    for k = 1 : K
        α_k = log(θ[k])
        u = (xNew - μ[k, :])./σ[k , :]
        β_k = sum(log.(σ[k, :])) + sum(u.*u)/2 
        scores[k]= α_k - β_k
    end
    argmax(scores)
end

function evaluate(X, y, θ, μ, σ)
    N = length(y)
    ŷ = zeros(N)
    for i=1:N
        ŷ[i] = classify(X[i, :], θ, μ, σ)
    end
    sum(y .== ŷ)/N
end

evaluate (generic function with 1 method)

In [48]:
X = A[:, 3:end]

569×30 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.7119  0.2654   0.4601  0.1189
 20.57   17.77  132.9   1326.0  0.08474     0.2416  0.186    0.275   0.08902
 19.69   21.25  130.0   1203.0  0.1096      0.4504  0.243    0.3613  0.08758
 11.42   20.38   77.58   386.1  0.1425      0.6869  0.2575   0.6638  0.173
 20.29   14.34  135.1   1297.0  0.1003      0.4     0.1625   0.2364  0.07678
 12.45   15.7    82.57   477.1  0.1278   …  0.5355  0.1741   0.3985  0.1244
 18.25   19.98  119.6   1040.0  0.09463     0.3784  0.1932   0.3063  0.08368
 13.71   20.83   90.2    577.9  0.1189      0.2678  0.1556   0.3196  0.1151
 13.0    21.82   87.5    519.8  0.1273      0.539   0.206    0.4378  0.1072
 12.46   24.04   83.97   475.9  0.1186      1.105   0.221    0.4366  0.2075
 16.02   23.24  102.7    797.8  0.08206  …  0.1459  0.09975  0.2948  0.08452
 15.78   17.89  103.6    781.0  0.0971      0.3965  0.181    0.3792  0.1048
 19.17   24.8   132.4   1123.0  0.0974      0.3639  0.1767 

In [49]:
(θ, μ, σ) = train(X, y)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.32346792452830186 0.09152995283018867; 12.146523809523813 17.914761904761903 … 0.27024593837535005 0.07944207282913165], [3.203971100779367 3.779469920776341 … 0.0746849560686125 0.02155288851442655; 1.7805116461410393 3.995124593675911 … 0.0417447664287058 0.013804045110823396])

In [81]:
size(μ)

(2, 30)

In [82]:
size(σ)

(2, 30)

In [83]:
evaluate(X, y, θ, μ, σ)

0.9402460456942003

In [6]:
A=[3 5 6;4 5 6;6 6 5]

3×3 Array{Int64,2}:
 3  5  6
 4  5  6
 6  6  5

In [8]:
sum(Int.(A[:,:]).==5)

3

LoadError: UndefVarError: Sum not defined